artifacts_root: artifacts



data_ingestion:
  root_dir: artifacts/data_ingestion 
  source_url: pranjal01/Text-summarizer-dataset  
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion













